// Hero datas (talents etc.)

const heroesData = [
	{'name': 'Abathur', 'attackDamage': 27.0, 'attackSpeed': 1.43},
	{'name': 'Alarak', 'attackDamage': 156.0, 'attackSpeed': 1.2},
	{'name': 'Alextrasza', 'attackDamage': 76.0, 'attackSpeed': 1.0},
	{'name': 'Ana', 'attackDamage': 31.0, 'attackSpeed': 1.33},
	{'name': 'Anduin', 'attackDamage': 88.4, 'attackSpeed': 0.83},
	{'name': 'Anub\'arak', 'attackDamage': 84.2, 'attackSpeed': 1.0},
	{'name': 'Artanis', 'attackDamage': 115.0, 'attackSpeed': 1.0},
	{'name': 'Arthas', 'attackDamage': 99.0, 'attackSpeed': 1.0},
	{'name': 'Auriel', 'attackDamage': 66.7, 'attackSpeed': 1.25},
	{'name': 'Azmodan', 'attackDamage': 88.0, 'attackSpeed': 1.0},
	{'name': 'Blaze', 'attackDamage': 57.0, 'attackSpeed': 1.0},
	{'name': 'Brightwing', 'attackDamage': 84.0, 'attackSpeed': 1.11},
	{'name': 'Cassia', 'attackDamage': 130.0, 'attackSpeed': 1.11},
	{'name': 'Chen', 'attackDamage': 93.6, 'attackSpeed': 1.11},
	{'name': 'Cho', 'attackDamage': 136.1, 'attackSpeed': 0.91},
	{'name': 'Chromie', 'attackDamage': 85.3, 'attackSpeed': 1.0},
	{'name': 'D.va', 'attackDamage': 22.9, 'attackSpeed': 4.0},
	{'name': 'Deathwing', 'attackDamage': 161.2, 'attackSpeed': 0.67},
	{'name': 'Deckard', 'attackDamage': 65.7, 'attackSpeed': 0.91},
	{'name': 'Dehaka', 'attackDamage': 104.0, 'attackSpeed': 1.11},
	{'name': 'Diablo', 'attackDamage': 109.0, 'attackSpeed': 0.95},
	{'name': 'E.T.C.', 'attackDamage': 103.0, 'attackSpeed': 1.25},
	{'name': 'Falstad', 'attackDamage': 108.0, 'attackSpeed': 1.43},
	{'name': 'Fenix', 'attackDamage': 86.3, 'attackSpeed': 1.85},
	{'name': 'Gal', 'attackDamage': 0.0, 'attackSpeed': 0.0},
	{'name': 'Garrosh', 'attackDamage': 142.0, 'attackSpeed': 0.83},
	{'name': 'Gazlowe', 'attackDamage': 104.0, 'attackSpeed': 1.25},
	{'name': 'Genji', 'attackDamage': 137.3, 'attackSpeed': 1.0},
	{'name': 'Greymane', 'attackDamage': 154.0, 'attackSpeed': 1.0},
	{'name': 'Gul\'dan', 'attackDamage': 61.9, 'attackSpeed': 1.0},
	{'name': 'Hanzo', 'attackDamage': 205.9, 'attackSpeed': 0.67},
	{'name': 'Hogger', 'attackDamage': 156.0, 'attackSpeed': 0.73},
	{'name': 'Illidan', 'attackDamage': 81.0, 'attackSpeed': 1.82},
	{'name': 'Imperius', 'attackDamage': 126.9, 'attackSpeed': 0.83},
	{'name': 'Jaina', 'attackDamage': 61.9, 'attackSpeed': 1.0},
	{'name': 'Johanna', 'attackDamage': 103.0, 'attackSpeed': 0.91},
	{'name': 'Junkrat', 'attackDamage': 124.8, 'attackSpeed': 1.0},
	{'name': 'Kael\'thas', 'attackDamage': 67.9, 'attackSpeed': 1.11},
	{'name': 'Kel\'Thuzad', 'attackDamage': 74.9, 'attackSpeed': 1.0},
	{'name': 'Kerrigan', 'attackDamage': 119.6, 'attackSpeed': 1.25},
	{'name': 'Kharazim', 'attackDamage': 66.7, 'attackSpeed': 2.0},
	{'name': 'Leoric', 'attackDamage': 119.6, 'attackSpeed': 0.77},
	{'name': 'Li Li', 'attackDamage': 61.9, 'attackSpeed': 1.25},
	{'name': 'Li-Ming', 'attackDamage': 65.5, 'attackSpeed': 1.0},
	{'name': 'Lt. Morales', 'attackDamage': 86.0, 'attackSpeed': 1.0},
	{'name': 'Lucio', 'attackDamage': 95.0, 'attackSpeed': 0.8},
	{'name': 'Lunara', 'attackDamage': 94.0, 'attackSpeed': 1.11},
	{'name': 'Maiev', 'attackDamage': 150.8, 'attackSpeed': 1.11},
	{'name': 'Mal\'Ganis', 'attackDamage': 95.7, 'attackSpeed': 0.91},
	{'name': 'Malfurion', 'attackDamage': 61.9, 'attackSpeed': 1.11},
	{'name': 'Malthael', 'attackDamage': 85.3, 'attackSpeed': 0.91},
	{'name': 'Medivh', 'attackDamage': 83.0, 'attackSpeed': 1.0},
	{'name': 'Mei', 'attackDamage': 78.0, 'attackSpeed': 1.0},
	{'name': 'Mephisto', 'attackDamage': 68.6, 'attackSpeed': 1.0},
	{'name': 'Muradin', 'attackDamage': 92.1, 'attackSpeed': 1.11},
	{'name': 'Murky', 'attackDamage': 61.9, 'attackSpeed': 1.25},
	{'name': 'Nazeebo', 'attackDamage': 92.1, 'attackSpeed': 1.11},
	{'name': 'Nova', 'attackDamage': 109.0, 'attackSpeed': 1.0},
	{'name': 'Orphea', 'attackDamage': 91.5, 'attackSpeed': 1.2},
	{'name': 'Probius', 'attackDamage': 34.0, 'attackSpeed': 1.11},
	{'name': 'Qhira', 'attackDamage': 104.0, 'attackSpeed': 1.0},
	{'name': 'Ragnaros', 'attackDamage': 187.2, 'attackSpeed': 0.83},
	{'name': 'Raynor', 'attackDamage': 105.1, 'attackSpeed': 1.25},
	{'name': 'Rehgar', 'attackDamage': 110.2, 'attackSpeed': 1.25},
	{'name': 'Rexxar', 'attackDamage': 139.4, 'attackSpeed': 0.87},
	{'name': 'Samuro', 'attackDamage': 106.0, 'attackSpeed': 1.67},
	{'name': 'Sgt. Hammer', 'attackDamage': 146.0, 'attackSpeed': 1.0},
	{'name': 'Sonya', 'attackDamage': 87.0, 'attackSpeed': 1.25},
	{'name': 'Stitches', 'attackDamage': 88.0, 'attackSpeed': 0.91},
	{'name': 'Stukov', 'attackDamage': 271.6, 'attackSpeed': 0.67},
	{'name': 'Slyvanas', 'attackDamage': 84.2, 'attackSpeed': 1.67},
	{'name': 'Tassadar', 'attackDamage': 14.6, 'attackSpeed': 4.0},
	{'name': 'The Butcher', 'attackDamage': 135.0, 'attackSpeed': 1.11},
	{'name': 'The Lost Vikings', 'attackDamage': 253.3, 'attackSpeed': 1.11},
	{'name': 'Thrall', 'attackDamage': 180.0, 'attackSpeed': 0.91},
	{'name': 'Tracer', 'attackDamage': 23.9, 'attackSpeed': 5.0},
	{'name': 'Tychus', 'attackDamage': 52.1, 'attackSpeed': 4.0},
	{'name': 'Tyrael', 'attackDamage': 81.0, 'attackSpeed': 1.25},
	{'name': 'Tyrande', 'attackDamage': 57.2, 'attackSpeed': 1.33},
	{'name': 'Uther', 'attackDamage': 78.0, 'attackSpeed': 1.0},
	{'name': 'Valeera', 'attackDamage': 82.0, 'attackSpeed': 2.0},
	{'name': 'Valla', 'attackDamage': 78.0, 'attackSpeed': 1.67},
	{'name': 'Varian', 'attackDamage': 77.0, 'attackSpeed': 1.25},
	{'name': 'Whitemane', 'attackDamage': 64.5, 'attackSpeed': 1.0},
	{'name': 'Xul', 'attackDamage': 98.8, 'attackSpeed': 1.21},
	{'name': 'Yrel', 'attackDamage': 161.2, 'attackSpeed': 0.77},
	{'name': 'Zagara', 'attackDamage': 88.4, 'attackSpeed': 1.25},
	{'name': 'Zarya', 'attackDamage': 21.0, 'attackSpeed': 4.0},
	{'name': 'Zeratul', 'attackDamage': 130.9, 'attackSpeed': 1.11},
	{'name': 'Zul\'jin', 'attackDamage': 97.8, 'attackSpeed': 1.25},
];